# Generated by Django 4.2.1 on 2023-06-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_addbook_addstudent_issuebook_returnbook_userextend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbook',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='returnbook',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='userextend',
            old_name='user',
            new_name='user2',
        ),
    ]
