# Generated by Django 4.2.1 on 2023-06-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_rename_user_addbook_user2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
