# Generated by Django 4.2.1 on 2023-06-11 18:51

import authsystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0006_bookreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreservation',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='book2',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='expirydate1',
            field=models.DateField(default=authsystem.models.expiry),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='reservedate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='studenid2',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
