# Generated by Django 4.2.1 on 2023-06-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0007_remove_bookreservation_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreservation',
            old_name='studenid2',
            new_name='studentid2',
        ),
    ]
