# Generated by Django 4.2.1 on 2023-06-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0009_reservedbook_delete_bookreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservedbook',
            old_name='user2',
            new_name='user',
        ),
    ]
