# Generated by Django 4.2.1 on 2023-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0010_rename_user2_reservedbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
