# Generated by Django 4.2.1 on 2023-06-20 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0013_remove_borrowbook_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
