# Generated by Django 4.2.1 on 2023-06-20 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0014_borrowbook_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='user2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
