# Generated by Django 4.2.1 on 2023-06-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0016_alter_borrowbook_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='Brequest',
            field=models.BooleanField(default=False),
        ),
    ]
