# Generated by Django 4.2.1 on 2023-06-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0017_addbook_brequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='Brequest',
            field=models.CharField(max_length=50),
        ),
    ]
