# Generated by Django 4.2.1 on 2023-06-20 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0018_alter_addbook_brequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedbook',
            name='user',
        ),
        migrations.AddField(
            model_name='reservedbook',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='is_reserved',
            field=models.CharField(max_length=50),
        ),
    ]
