# Generated by Django 4.2.1 on 2023-06-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0020_renewbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewBook',
        ),
    ]
