# Generated by Django 4.2.1 on 2023-06-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0021_delete_renewbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='studentid',
            new_name='username',
        ),
    ]
