# Generated by Django 4.2.1 on 2023-06-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0022_rename_studentid_borrowbook_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='username',
            new_name='studentid',
        ),
    ]
