# Generated by Django 4.2.1 on 2023-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0025_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='sem',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
